---

services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 1000:1000 # <-- Your PUID & PGID
    networks:
      - your-network # <---Add your network name here
    volumes:
      - ./filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-browser.entrypoints=http"
      - "traefik.http.routers.file-browser.rule=Host(`file.yourdomain.com`)" # <-- Your domain name here
      - "traefik.http.middlewares.file-browser-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.file-browser.middlewares=file-browser-https-redirect"
      - "traefik.http.routers.file-browser-secure.entrypoints=https"
      - "traefik.http.routers.file-browser-secure.rule=Host(`file.yourdomain.com`)" # <-- Your domain name here
      - "traefik.http.routers.file-browser-secure.tls=true"
      - "traefik.http.routers.file-browser-secure.service=file-browser"
      - "traefik.http.services.file-browser.loadbalancer.server.port=80"
      - "traefik.docker.network=your-network" # <---Add your network name here
networks:
  your-network: # <---Add your network name here
    external: true
