---

title: iSOFT Cloud Homepage #  <-- you can change title of home page
favicon: https://isoft.com.lk/favicon.ico #  <-- you can change favicon icon
theme: dark # <----- add this line
color: slate # <----- add this line
disableCollapse: true

background:
  image: https://images.unsplash.com/photo-1689443111130-6e9c7dfd8f9e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D #  <-- you can change background image
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 80 # 0-100
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# for add icons for service titles
# https://mdi.bessarabov.com

layout:
  Proxy and DNS:
    icon: mdi-server-network-#FFFFFF
  Security & Identity:
    icon: mdi-server-#FFFFFF
  Management:
    icon: mdi-auto-fix-#FFFFFF
  Monitoring:
    icon: mdi-list-status-#FFFFFF
 